language: go

sudo: false

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      go: 1.x
    - os: osx
      go: 1.x
    - os: windows
      go: 1.x

before_install:
  - go get golang.org/x/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go test -v ./...
